#!/usr/bin/env bash

function f_ssh_client_send_command(){
  ssh_command=$1
  ssh -i ~/.ssh/${v_key_name}.pem -o "StrictHostKeyChecking no" ${v_ssh_user}@$(f_get_instance_public_dns $(f_get_instance_id)) ${ssh_command}
}

function f_wait_for_ssh(){
  while true; do
    until [[ $_ssh_availability -eq 1 ]]; do
      sleep ${v_wait_seconds}
      f_test_ssh
    done
    break
  done
}

function f_test_ssh(){
  exec 3>&2
  exec 2> /dev/null
  ssh -i ~/.ssh/${v_key_name}.pem -o "StrictHostKeyChecking no" ${v_ssh_user}@`f_get_instance_public_dns $(f_get_instance_id)` echo ""
  if [ $? -eq 0 ]; then
    _ssh_availability=1
    echo -e "\t\t\t\tSSH Available"
  else
    _ssh_availability=0
    echo -e "\t\t\t\tpending"
  fi
  exec 2>&3
}
