#!/usr/bin/env bash

function f_create_security_group(){
  aws ec2 create-security-group --group-name ${v_security_group} --description "${v_security_group_desc}" >> ${v_params}
}

function f_allow_ports(){
  for i in ${v_allowed_ports}; do
    aws ec2 authorize-security-group-ingress --group-name ${v_security_group} --to-port ${i} --ip-protocol ${v_ip_proto} --cidr-ip ${v_allowed_nets} --from-port ${i}
  done
}

function f_allow_self(){
  aws ec2 authorize-security-group-ingress --group-name ${v_security_group} --protocol -1 --port -1 --source-group $(f_get_security_group_id)
}

function f_delete_security_group(){
  aws ec2 delete-security-group --group-name ${v_security_group}
}

function f_get_security_group_id(){
  aws ec2 describe-security-groups --group-names ${v_security_group} --query "SecurityGroups[].[GroupId]" --output text
}
