#!/usr/bin/env bash

function f_print_help(){
  echo -e "\n\tUsage: ./`basename \"$0\"` [ --deploy | --cleanup | --help ]\n"
  echo -e "\t\t--deploy\t\tDeploys the ${v_project} environment"
  echo -e "\t\t--cleanup\t\tTears down the ${v_project} Workbook environment"
  #echo -e "\t\t--increase-Load\t\tRuns processes in autoscaled instances to spike CPUUtilization"
  echo -e "\t\t--help\t\t\tDisplays this message\n"
}
